// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: qthxwsnrfbsriqzklkgn

class SupabaseConfig {
  static const String supabaseUrl = 'https://qthxwsnrfbsriqzklkgn.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0aHh3c25yZmJzcmlxemtsa2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU3MjE5MjYsImV4cCI6MjA4MTI5NzkyNn0.BV_x2tmqnexnPzq-9mGvO1BJP0fcrBISs3i9wBoXic4';
}
